core/request_builder.go

The new feature for document translator in LTV3 gave a `request canceled (Client.Timeout exceeded while awaiting headers` as the server didnt like a request containing an extra semicolon in the request:
`Content-Disposition: form-data; name="model_id";`

fix(request-builder): Fix for semicolon in building form param

---

core/authenticator_factory_test.go
core/base_service_test.go
core/config_utils.go
core/config_utils_test.go
resources/my-credentials.env

This PR includes a small change to config_utils.go that adds the required transformation of the credential key (service name) when using it to form the names of external config properties in credential files or environment variables.
The transformation is essentially to replace - with _ and to fold the credential key to upper case, then use it to form a cred file property or environment variable name.

feat: support correct service key transformations when loading external config properties

---

core/base_service.go
core/base_service_test.go
core/detailed_response.go
core/detailed_response_test.go

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/999
This PR enhances the Go core's ability to return as much information as possible from the operation response in the DetailedResponse structure.
Highlights of changes:
1. In the case of a successful invocation:
* if the response body is not JSON, we'll return it as a byte array in the new `DetailedResponse.RawResult` field.
2. In the case of an unsuccessful invocation:
* (as before) we'll obtain an error message from the response body and return it in an error object.
* (new) we'll decode the entire response body (presumably containing an error structure) as a map and return it in the `DetailedResponse.Result` field.
3. Added new DetailedResponse methods to retrieve the RawResult and Result (as map) values.

feat: return more information in the DetailedResponse

---

core/base_service.go
core/base_service_test.go
core/basic_authenticator_test.go
core/bearer_token_authenticator_test.go
core/cp4d_authenticator.go
core/iam_authenticator.go
core/noauth_authenticator_test.go
core/request_builder.go
core/request_builder_test.go

Fixes arf/planning-sdk-squad#1011
Why:
In order to support parameterized URLs, we need to defer the validation of
the service URL value (i.e. myservice.Service.Options.URL) to the point at
which it is first needed, instead of when the BaseService struct is
constructed.
What:
This PR contains changes to support the above, plus the following:
1) Added comments here and there to some public structs and methods.
2) Made certain elements within BaseService private since they're not needed
outside BaseService.
3) Removed the Version field from the ServiceOptions struct.  Instead, the
Go generator will be changed to define Version as a field of the generated
service struct (e.g. AssistantV1) only when the service is detected to
use a "version param".  The Go core has no use for the Version field …

Defer service URL validation

---

.releaserc
.travis.yml
core/config_utils.go

This PR handles:
* Updates to semantic release to include changelog
* When checking for credentials, check for working dir before home dir

Semantic and change order of files for adding creds

---

core/base_service.go
core/constants.go

This PR adds description on how to disable ssl verification.
The error that was thrown was:
```
Get https://blissful-tharp-balancer.fyre.ibm.com:31843/watson/discovery/zen-flunky/instances/1568641354/api/v1/environments: x509: certificate is valid for internal-nginx-svc, *.svc.cluster.local, api-svc, *.api, ibm-nginx-svc, localhost, dsxl-api, not blissful-tharp-balancer.fyre.ibm.com
``` 
from https://golang.org/src/crypto/x509/verify.go
Go doesn't seem to be having specific ways of catching an error, so this seems to be the best I could think of

feat(disable ssl): Add description on disabling ssl verification

---

.gitignore
core/constants.go

Fixes: https://github.ibm.com/Watson/developer-experience/issues/7580

fix: use correct error message for SSL verification errors

---

.gitignore
.gometalinter.json
core/request_builder.go
core/request_builder_test.go

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/1073
The RequestBuilder.ConstructHTTPURL function was updated so that it doesn't add a "/" to the URL string if the path segment is "".
This could occur if the operation's path contains two consecutive path parameter references, as in:
```
"/v1/resource/{resource_type}/{resource_id}"
```
The VPC API definition defines a couple of paths that fit this pattern.
The API handbook "disallows" this, but we should probably support it nonetheless.

fix: fixed ConstructHTTPURL to avoid '//' when path segment is empty string

---

.bumpversion.cfg
.travis.yml
core/version.go

This PR attempts to fix the mess created by semantic-release/bumpversion where the 1.0.0 version of the go core repo contains a version.go that specifies 0.8.0

fix: fix version.go and .bumpversion.cfg for 1.0.0 release

---

core/base_service.go
core/base_service_test.go

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/1131
Changes:
- moved the external configuration code outside of the constructor into it's own method.
- for compatibility, the constructor calls the new method until we move to the service factory's complete implementation.
The new method will now be invoked from the generator after the BaseService's constructor is called. I have made the method public so it is accessible from the service instance.

feat(BaseService): add new method ConfigureService() to BaseService struct

---

core/authenticator_factory_test.go
core/base_service.go
core/base_service_test.go
core/config_utils.go
core/config_utils_test.go
resources/vcap_services.json

Go core changes for https://github.ibm.com/arf/planning-sdk-squad/issues/1097
Changes:
- Call ConfigureService from the BaseService.
- Add a name field to the service interface. 
- Create a list of service entries and check for the service name within them before checking the keys to the service entry lists.
- Update unit test to check that `loadFromVCAPServices` is looking for service credentials from the VCAP in the correct order.

feat(loadFromVCAPServices): Update VCAP services to check service entry names before keys to service entry lists.

---

core/request_builder.go

This adds support for the HEAD method, which is used by an operation in the IAM Access Groups platform service.  Now, operations generated with `core.HEAD` will work as expected.

fix: add HEAD operation constant

---

core/base_service.go
core/base_service_test.go
core/detailed_response.go

This PR will allow the generated Go code to support a scenario where the decoding of a JSON response body is bypassed with the response body being returned in the DetailedResponse.Result field as an io.ReadCloser instance.
To do this, the generated code would pass in the result of `new(io.ReadCloser)` instead of `new(Foo)` for the deserialization target result object (where Foo represents a model object).

feat: allow JSON response body to be streamed

---

.bumpversion.cfg
.releaserc
.travis.yml
core/version.go

This PR allows us to use bump2version (a more recent fork of bumpversion) to maintain the major version # within the go.mod file.

Maintain major version # in go.mod file via bump2version

---

core/unmarshal.go
core/unmarshal_test.go

This PR is part of the fix for https://github.ibm.com/arf/planning-sdk-squad/issues/1465
This PR adds a couple of extra "Unmarshal" methods for "Any" which will be used by the Go generator for properties associated with an empty schema.

feat: add unmarshal functions for 'any'

---

core/base_service.go
core/base_service_test.go

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/1483
This PR improves the BaseService.getErrorMessage() function so that it is more tolerant of
error responses that might not comply 100% with a "standard" error response structure.

fix: tolerate non-compliant error response bodies

---

core/base_service_test.go
core/basic_authenticator.go
core/bearer_token_authenticator.go
core/cp4d_authenticator.go
core/iam_authenticator.go
core/iam_authenticator_test.go
core/noauth_authenticator.go

This PR makes a small but important fix to the IAM and CP4D authenticators that fixes the way tokens are cached for future use.  Previously, the `authenticator` passed to the `Authenticate` method was passed by value, and when the token was stored into this authenticator, it was lost when the `Authenticate` method returned.  The fix is to pass the authenticator to `Authenticate` _by reference_, so that the token is stored in the caller's `authenticator` object and then available for subsequent calls.

Fix caching of access tokens

---

core/unmarshal.go
core/unmarshal_test.go

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/1517
Fixes: https://github.ibm.com/ibmcloud/platform-services-go-sdk/issues/14
This PR adds an explicit nil check when retrieving properties from a map inside the various UnmarshalXXX() methods.   Previously, we were checking for the existence of the property in the map, but did not consider the possibility that the value of the property is the JSON null value.

fix: tolerate explicit JSON null values in UnmarshalXXX() methods

---

core/unmarshal.go
core/unmarshal_test.go

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/1613
This PR is part 1 of the fix.  It contains new core methods for unmarshalling maps of various primitive types.   The Go generator will be updated to use these new methods when generating the code to unmarshal a model property that is a generic map of string to `<primitive-type>`, where `<primitive-type>` could be string, []byte, bool, int64, float32, float64, UUID, Date, DateTime.
If a model property is defined as a generic map of string to "anything" (map[string]interface{}), then we'll just use the existing UnmarshalObject() method.

feat: add unmarshal methods for maps of primitive types

---

core/base_service.go
core/base_service_test.go
core/unmarshal_v2.go
core/unmarshal_v2_models_test.go
core/unmarshal_v2_primitives_test.go
go.sum

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/1613
This PR contains new unmarshal functions for primitive and model types in the Go core.
This will be needed in the SDK generator changes to fix the referenced issue.
The "new" approach for unmarshalling JSON values (primitives and models) in the Go generator will be to generate a single `Unmarshal<model>()` function for each model.   This generated function can then be passed as a parameter (along with the JSON input and a pointer to the unmarshal result) to the core's UnmarshalModel() function.  UnmarshalModel() will use reflection to interpret the JSON input and the result to determine the appropriate type of unmarshal operation (e.g. a single model instance, a slice of models, a map of models, or a map of model slices). …

feat(unmarshal): introduce new unmarshal functions for primitives and models

---

core/config_utils.go
core/config_utils_test.go
go.mod
go.sum
resources/my-credentials.env

This PR allows external config property values to contain an "=".
Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/1759

fix: allow = in config property values

---

v4/core/unmarshal_v2.go
v4/core/unmarshal_v2_models_test.go

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/1818
This PR changes the Go core UnmarshalModel() functionality so that it will correctly handle scenarios where JSON input does not contain a value at all for a particular property or it contains an explicit JSON "null" value.   In each case, we'd expect to get back a nil result when unmarshalling into a slice or map.   Previously we'd get back an empty slice or map instead, which is not correct.

fix: correctly unmarshal JSON 'null' value for maps and slices

---

v4/core/request_builder.go
v4/core/request_builder_test.go

`RequestBuilder.SetBodyContent` currently does not correctly handle the case when its `interface{}` arguments are nil pointers. 
In Go, a `interface{}(*string)(nil)` is not the same as `nil`. This is because `interface{}`s are essentially a box containing an underlying type and value; there are cases where this method is given arguments where the box contains an empty pointer, but the box itself is not `nil`, thereby causing the wrong body contents to be set.
I discovered this bug when trying (and failing) to use plain text with IBM's Tone Analysis API and always getting an empty reply. This is because `SetBodyContent` always encodes with the (nil) `jsonContent` instead of the (non-nil) plaintext body.
See the following delve debug logs for more information:

Correctly handle nil pointer interfaces in RequestBuilder.SetBodyContent

---

v4/core/detailed_response.go
v4/core/marshal_nulls_test.go

This PR simply adds a new test which verifies that a nil dynamic property value will be correctly serialized as a JSON "null" value.
In addition to the new test, I also needed to fix an unrelated linter error found in DetailedResponse.String().

Add test involving nil dynamic property values

---

v4/core/base_service.go
v4/core/utils.go
v4/core/utils_test.go

This PR contains a handful of minor changes to ensure that we're checking `interface{}` values for nil appropriately.
Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/1958

fix: use isNil() for interface{} values

---

v4/core/base_service.go
v4/core/base_service_test.go
v4/core/constants.go

This PR improves error reporting inside BaseService.Request().

fix: improve error paths in BaseService.Request()

---

v4/core/base_service.go
v4/core/request_builder.go
v4/core/utils.go
v4/core/utils_test.go

This PR renames the `isNil()` method to be `IsNil()` to make it public so that it can be used by generated code.

feat: rename isNil to be IsNil (public)

---

v4/core/utils_test.go

This PR improves our testing of the IsNil() function to include nil checks of various datatypes, including a model instance, map and slice

test: improve testing of IsNil()

---

v4/core/constants.go
v4/core/request_builder.go
v4/core/request_builder_test.go
v4/core/utils.go
v4/core/utils_test.go

This PR adds a new method, ``ConvertSlice`` which converts any non-string slice to a string slice using the go ``marshal`` method, along with string manipulation. 
I chose to return an empty slice if an error occurs during conversion to reduce the generated code needed to use this method, though if we feel it's best to return an error rather than an empty slice I'm not against that change. I've added test cases to hopefully capture all the realistic scenarios this method would be used in.
ref: https://github.ibm.com/arf/planning-sdk-squad/issues/1904

feat: add utility function to convert primitive type slices to string slices

---

v4/core/utils_test.go

This PR modifies `ValidateStruct` which only checks for non-nil parameter values to also check for parameter values that are the empty string. This matches behavior in the other cores.
Internal Tracking Issue: [#1908](https://github.ibm.com/arf/planning-sdk-squad/issues/1908)

fix: check for empty string path parameters

---

v4/core/authenticator.go
v4/core/cp4d_authenticator.go
v4/core/iam_authenticator.go

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/2144
This PR makes the "err" field public (i.e. "Err") and adds the `NewAuthenticationError()` ctor function.

fix: expose AuthenticationError.Err field and add ctor

---

v4/core/request_builder.go
v4/core/request_builder_test.go
v4/core/utils_test.go

Fixes arf/planning-sdk-squad#2152
This commit adds method ResolveRequestURL to the RequestBuilder struct
as a replacement for ConstructHTTPURL().

feat: add new RequestBuilder.ResolveRequestURL

---

v4/core/authenticator.go
v4/core/cp4d_authenticator.go
v4/core/cp4d_authenticator_test.go
v4/core/iam_authenticator.go
v4/core/iam_authenticator_test.go

Fixes a very unique scenario described in https://github.ibm.com/arf/planning-sdk-squad/issues/2149. In the scenario where a client has been idle passed the refresh time, but before expiration time, the previous logic would result in multiple goroutines being kicked off attempting to request a new token until a new token was fetched or until the refresh time caught up to the current time. I've updated the new ``refreshTime`` calculation to be 1 minute ahead of the __current time__ vs 1 minute ahead of the previous ``refreshTime`` value. 
Java also probably has this same issue so I will update that core as well.
ref: https://github.ibm.com/arf/planning-sdk-squad/issues/2149

fix: iam/cp4d token refresh logic

---

v4/core/authenticator_factory_test.go
v4/core/config_utils_test.go
v4/core/constants.go
v4/core/iam_authenticator.go
v4/core/iam_authenticator_test.go
v4/resources/my-credentials.env

The IAM /identity/token (get token)  operation supports an optional "scope"
form parameter which can be used to obtain an IAM access token
having a limited set of scopes in this it can be used.
This commit adds support for the "Scope" field within
the IamAuthenticator struct.  If set, the value of this field
is sent as the "scope" form param in the "get token"
request body when obtaining an access token.

feat(IAM Authenticator): add support for optional 'scope' property

---

v4/core/request_builder.go
v4/core/request_builder_test.go

Fixes a bug in which not setting any body type lead to an attempt to reflect the type of a `nil` object, which caused a panic. Explicitly handles the case in which all three potential body objects are `nil`. Adds a test for this case.

fix: dont panic in SetBodyContent when nonJSONContent is nil

---

v4/core/base_service.go
v4/core/base_service_test.go
v4/core/config_utils_test.go
v4/core/constants.go
v4/core/gzip.go
v4/core/gzip_test.go
v4/core/request_builder.go
v4/core/request_builder_test.go
v4/core/utils.go
v4/core/utils_test.go
v4/resources/my-credentials.env

Fixes arf/planning-sdk-squad#2185
This commit adds support for peforming gzip compression
of request bodies, and consists of the following:
1. Two new functions: NewGzipCompressionReader() and
NewGzipDecompressionReader().  Each function will wrap
an existing io.Reader to provide compression/decompression
using a filter pattern.
2. A new field "EnableGzipCompression" was added to the
RequestBuilder struct to indicate whether or not request
bodies should be gzip-compressed.
3. RequestBuilder.Build() was updated to honor the new flag
and (if enabled) wrap the Body field in a gzip compression filter
prior to constructing the http.Request instance.

feat: add support for gzip compression of request bodies

---

v4/core/iam_authenticator.go
v4/core/iam_authenticator_test.go

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/2215
This PR exposes IamAuthenticator.requestToken() as a public method, along with the IamTokenServerResponse struct which is returned by requestToken().

fix: expose IamAuthenticator.requestToken as a public method

---

.travis.yml
CONTRIBUTING.md
README.md
v4/core/request_builder.go
v4/core/request_builder_test.go

Fixes arf/planning-sdk-squad#2230
Fixes #77
This commit adds support for setting a Context
instance on the RequestBuilder struct.  This Context instance
will then be associated with the http.Request instance constructed
by the RequestBuilder.Build() method.
The Context can be used to define a timeout/deadline for a request
or to cancel an in-flight request.

feat: support use of Context with RequestBuilder

---

v4/core/cp4d_authenticator.go
v4/go.mod
v4/go.sum

This upgrade changes the `dgrijalva/jwt-go v3.2.0` to use `form3tech-oss/jwt-go v3.2.1`, a fork which as addressed the high severity security vulnerability.
There has been a lot of conversation about this fix in https://github.com/dgrijalva/jwt-go/issues/428, but this project is not maintained by its authors and a fix to this project seems unlikely given this conversation.

fix: jwt dependency upgrade

---

v4/core/config_utils_test.go
v4/core/request_builder_test.go
v4/resources/ibm-credentials.env

Watson gateway urls are being deprecated and will cease to function after 12 Feb 2021. This pull request updates the watsonplatform.net urls to the corresponding onecloud urls.

Update gateway url

---

v4/core/base_service.go
v4/core/base_service_test.go

This commit adds the BaseService "Clone()" method that can be
used to make a copy of an existing BaseService instance as part
of cloning a generated service struct instance.

feat(BaseService): add Clone() method to clone a BaseService instance

---

.gitignore
Authentication.md
v4/core/base_service_test.go
v4/core/constants.go
v4/core/cp4d_authenticator.go
v4/core/cp4d_authenticator_test.go
v4/core/jwt_utils.go
v4/core/jwt_utils_test.go
v4/go.mod
v4/go.sum

Fixes arf/planning-sdk-squad#2344
This commit enhances the CP4D Authenticator to support
the username/apikey use case.  With these changes, a user
has the ability to construct a CP4D authenticator using either
a username/password pair or a username/apikey pair.
The authenticator will now use the official
"POST /v1/authorize" operation for obtaining an access token.

feat: support username/apikey use-case in CloudPakForDataAuthenticator

---

v5/core/base_service.go
v5/core/base_service_retries_test.go
v5/core/base_service_test.go
v5/core/constants.go
v5/core/unmarshal_v2.go
v5/core/unmarshal_v2_models_test.go

This PR addresses a corner case in the base_service `Request` method where it could return a nil `err` but not set the `result` value passed by the user.  This behavior would force users to check explicitly for `result != nil` in addition to checking for `err == nil`, which is a poor experience for the user, particularly since they will likely just manufacture an error for this case anyway.
I also made a small change to check for a nil input to `UnmarshallModel`, since this method should treat this condition as an error rather than silently returning and empty result as it had been.
Tests are updated.

fix: ensure result value is set if err is nil

---

v5/core/cp4d_authenticator_test.go
v5/core/iam_authenticator.go
v5/core/iam_authenticator_test.go

This commit includes two changes:
1. The IAM Authenticator is now more flexible with respect to the
configured IAM url specified by the user.  The path part ("/identity/token")
is now optional.
2. For errors returned by the IAM token server, if the response received
from the token server does not contain an error message, then a default
error message containing the unexpected status code will be returned rather
than an empty string.

fix(IAM Authenticator): canonicalize iam url & improve iam error reporting

---

v5/core/datetime.go
v5/core/datetime_test.go
v5/core/utils.go
v5/core/utils_test.go

Add helper methods for casting strfmt UUID, Date, and DateTime literals to pointers needed by the go setter methods. Also, this is only parsing dates with RFC3339. This likely needs to be updated in the future to allow other formats to be used.
This is used in the sdk generator PR #873

feat: add UUID, date, and datetime helpers for terraform usage

---

v5/core/utils.go
v5/core/utils_test.go

This PR adds a small utility method to extract the value of a query parameter from a URL string.  This will be used in the pagination support for Go.

Add GetQueryParam utility method to support pagination

---

v5/core/base_service.go
v5/core/base_service_retries_test.go
v5/core/base_service_test.go
v5/core/cp4d_authenticator.go
v5/core/cp4d_authenticator_test.go
v5/core/iam_authenticator.go
v5/core/iam_authenticator_test.go

Fixes arf/planning-sdk-squad#2440
There were several warnings about race conditions (mostly about the `tokenData` field) when running the unit tests. 
`go test -tags=all -race`
Introduced "getter" and "setter" functions for the authenticator's `tokenData` with mutex.

fix: data race warnings

---

v5/core/unmarshal_v2.go
v5/core/unmarshal_v2_models_test.go
v5/core/unmarshal_v2_primitives_test.go

This commit improves the model unmarshalling capabilities within the Go core
by adding support for an additional pattern ([][]MyModel) within the
UnmarshalModel() function.  The full set of patterns now supported are:
- MyModel (model instance)
- map[string]MyModel (map containing model instances)
- map[string][]MyModel (map contains slices of model instances
- []MyModel (slice of model instances)
- new: [][]MyModel (slice of model instance slices)

feat: add support for unmarshalling two-dimensional slices of model instances

---

.travis.yml

This PR updates the version of the golangci-lint package in the travis config to fix linter errors during travis builds.
**Fixes:** https://github.ibm.com/arf/planning-sdk-squad/issues/2565

build: update golangci-lint version in travis config

---

v5/core/config_utils.go

This was flagged as a potential vulnerability by the ASOC scans.

chore: ignore false positive codescan

---

v5/core/cp4d_authenticator.go
v5/core/iam_authenticator.go

This PR fixes some possible goroutine leak in the authenticators' `getToken` methods.
Closes #108

fix: eliminate goroutine leak in the authenticators

---

v5/core/file_with_metadata.go
v5/core/file_with_metadata_test.go

FileWithMetadata is a struct that contains the binary data within a file, along
with specific metadata: the filename and the content type. This is a type that
the generated code occasionally uses. Currently, we generate this type as a
model on a specific service but because it is service-independent, we want to
move it to the core. This adds it as a supported type within the core. Although
the generator won't be able to change this type in options models until the next
major relase, it will use this type in the generated unmarshall functions, which
are currently broken. This will be fixed in the generator after this feature is
released.
The new "unmarshaler" in the core includes code to parse the JSON
string and read the data from the file while creating the struct. Generated
unmarshaller …

feat: add FileWithMetadata type to the core

---

v5/core/datetime.go
v5/core/datetime_test.go

This PR adds empty string check to the `ParseDate` function. It's the same as the `strfmt` packages has in the `ParseDateTime` function. Tests have been updated.

feat: check for empty string in ParseDate

---

v5/core/cp4d_authenticator.go
v5/core/cp4d_authenticator_test.go
v5/core/iam_authenticator.go
v5/core/iam_authenticator_test.go

This PR renames the `getToken()` methods in the IAM authenticator and in the CP4D authenticator to `GetToken()`.

fix: make the get token method exported

---

v5/core/jwt_utils.go
v5/core/jwt_utils_test.go
v5/go.mod
v5/go.sum

This PR implements the `decodeSegment()` function from the JWT package that we have been using and also completely removes the JWT dependency from the project.
Ref: #121

chore: reimplement a JWT function to drop the dependency

---

v5/core/constants.go
v5/core/cr_authenticator.go

This commit changes the error message used by the
ComputeResourceAuthenticator to report a validation
error when neither of the `IAMProfileName` or `IAMProfileID`
properties are specified by the user.
The error message is now:
`At least one of IAMProfileName or IAMProfileID must be specified.`

fix: error message used by CR Authenticator

---

Authentication.md
README.md

This PR fixes 2 minor documentation issues:
- `README.md`: missing Container auth from the `Authentication` section
- Old reference in the `Authentication.md`: Compute Resource instead Container

docs: fix some container auth references

---

v5/core/constants.go
v5/core/container_authenticator.go
v5/core/cp4d_authenticator.go
v5/core/iam_authenticator.go

The [`nosec` annotations](https://github.com/securego/gosec#annotating-code) are not processed when the preceding content is followed by a comma.  I tried several permutations to see if I could get around this, but was unsuccessful.

chore: codescan updates

---

.travis.yml
Makefile

This PR updates the go core build so that it is built on go 1.12 and 1.16.

build: build on go 1.12 and 1.16

---

.travis.yml

In my previous PR where I added a build job for go 1.16, I should have also added 1.17.  My bad :)

build: add go 1.17

---

v5/core/gzip.go

This PR fixes/improves the error handling in the Gzip compression. Before this commit if an error occurred during the compression it caused a panic. With this change, in case of errors, the pipe will be closed and the error will be passed.

fix: handle the error during gzip compression instead of panic

---

v5/core/base_service.go
v5/core/base_service_test.go
v5/core/constants.go
v5/core/utils.go
v5/core/utils_test.go

This commit modifies the Go core response-handling code
so that it recognizes vendor-specific JSON-based mimetypes
(e.g. application/vnd.docker.distribution.manifest.v2+json)
as being equivalent to "application/json" when deciding how
to unmarshal an operation response body.
Prior to this change, the Go core would treat such a response
as an error.

fix: recognize vendor-specific JSON mimetypes

---

.cra/.cveignore
.secrets.baseline

Ignores the packr/v2 vulnerability until we can put a fix in place.

chore: add .cveignore

---

.secrets.baseline
.travis.yml
v5/core/container_authenticator.go
v5/core/cp4d_authenticator.go
v5/core/iam_authenticator.go

This PR tweaks a few of the inline code annotations used to ignore false-positive gosec violations.

fix: avoid false positive gosec errors

---

.secrets.baseline
v5/core/base_service.go
v5/core/base_service_test.go

This commit includes changes to the BaseService functionality
so that enabling automatic retries will not cause the loss of
any existing http.Client instance that might be set on the
BaseService.
A user can now use BaseService.SetHTTPClient() to set
a custom client instance with or without retries being enabled.
Also, the BaseService.GetHTTPClient() method was introduced
which will return the correct http.Client instance regardless
of whether retries are enabled or not.

fix: retain http.Client config when retries are enabled

---

.secrets.baseline
v5/core/iam_authenticator.go
v5/core/iam_authenticator_test.go

This commit adds a bit of leniency to the IamAuthenticator.Validate() method.
We need to do this to ensure that a single authenticator instance can be shared
among multiple service instances.

fix(IamAuthenticator): tweak Validate() method to be more lenient

---

.secrets.baseline
v5/core/utils.go
v5/core/utils_test.go
v5/go.sum

This commit introduces the "GetQueryParamAsInt()"
utility function that will be used by generated
code to perform automatic pagination.
Similar to GetQueryParam, but also converts
the retrieved value to an int64.

feat: add function GetQueryParamAsInt

---

.travis.yml

This commit enables building the project on Go 1.19.
It also updates the `golangci-lint` package version
to resolve a compatibility issue with the latest Go version.
Signed-off-by: Norbert Biczo <pyrooka@users.noreply.github.com>

build: add Go 1.19

---

v5/core/utils.go
v5/core/utils_test.go

We have pointer-creation functions for a few other types. There is now a need to have a function like this for byte arrays within our generated Terraform code, so I've added it alongside the others.
Signed-off-by: Dustin Popp <dpopp07@gmail.com>

feat(utils): add helper for creating a byte array pointer

---

v5/core/base_service.go

The method `BaseService.Request` invoked without result (`nil`) does not close `http.Response` and prevents connection to be put back into idle state.
We observed significant memory usage or quick `MaxConnsPerHost` limit exhaustion, when `BaseService.Request` is called with `nil` result.
Issue: https://github.com/IBM/go-sdk-core/issues/175

fix: BaseService.Request invoked without result does not close http.Response

---

core/authenticator_factory_test.go
core/base_service_test.go
core/common_test.go
core/config_utils_test.go
core/iam_authenticator_test.go

Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
Reference: https://pkg.go.dev/testing#T.Setenv
```go
func TestFoo(t *testing.T) {
// before
os.Setenv(key, "new value")
defer os.Unsetenv(key)
// after
t.Setenv(key, "new value")
}
```

test: use `t.Setenv` to set env vars

---

core/utils.go
core/utils_test.go

The RFC for content-type header format allows optional whitespace before the semicolon. Our regular expressions for recognizing various mime types do not account for this, so valid mime types may not be recognized. This commit adjusts the expression to close that gap.

fix(utils): recognize content types with whitespace

---

Authentication.md
core/container_authenticator.go

This commit adds support for a second default CR token filename. If the user doesn't specify a CR token filename, the authenticator will first try `/var/run/secrets/tokens/vault-token`, and then `/var/run/secrets/tokens/sa-token` in that order.

fix(ContainerAuthenticator): add sa-token as default CR token filename

---

.secrets.baseline
Authentication.md
README.md
core/authenticator_factory.go
core/authenticator_factory_test.go
core/common_test.go
core/constants.go
core/mcsp_authenticator.go
core/mcsp_authenticator_test.go
resources/my-credentials.env

This commit introduces the new MCSPAuthenticator that can be used to exchange an apikey for an MCSP access token using the Multi-Cloud Saas Platform authentication token server's 'POST /siusermgr/api/1.0/apikeys/token' operation.

feat(MCSPAuthenticator): add new authenticator for Multi-Cloud Saas Platform

---

.travis.yml
CONTRIBUTING.md
core/authenticator_factory_test.go
core/base_service_retries_test.go
core/base_service_test.go
core/basic_authenticator_test.go
core/bearer_token_authenticator_test.go
core/common_test.go
core/config_utils_test.go
core/container_authenticator_test.go
core/cp4d_authenticator_test.go
core/datetime_test.go
core/detailed_response_test.go
core/gzip_test.go
core/iam_authenticator_test.go
core/jwt_utils_test.go
core/log_test.go
core/marshal_nulls_test.go
core/mcsp_authenticator_test.go
core/noauth_authenticator_test.go
core/parameterized_url_test.go
core/request_builder_test.go
core/unmarshal_v2_models_test.go
core/unmarshal_v2_primitives_test.go
core/utils_test.go
core/vpc_instance_authenticator_test.go

This commit replaces the old Go build tag syntax with
the new one which was released in Go 1.17, since the
current one is deprecated and not used by any tools.
Docs: https://pkg.go.dev/cmd/go#hdr-Build_constraints
Signed-off-by: Norbert Biczo <pyrooka@users.noreply.github.com>

build: update build lines and the contributing docs

---

.travis.yml
README.md
go.mod

This commit adds the latest Go version to the builds (`1.22`)
and removes the oldest one (`1.19`), so now the minimum
version is `1.20`.

build: bump Go versions

---

.secrets.baseline
core/container_authenticator_test.go
core/iam_authenticator.go
core/iam_authenticator_test.go
core/vpc_instance_authenticator_test.go

This commit changes the IAM, Container and VPC Instance authenticators slightly so that an IAM access token will be viewed as "expired" when the current time is within 10 seconds of the official expiration time. IOW, we'll expire the access token 10 secs earlier than the IAM server-computed expiration time.
We're doing this to avoid a scenario where
an IBM Cloud service receives a request along
with an "almost expired" access token and then uses that token to perform downstream requests in a
somewhat longer-running transaction and then the
access token expires while that transaction is
still active.

fix: adjust IAM token expiration time

---

core/base_service.go
core/basic_authenticator.go
core/bearer_token_authenticator.go
core/config_utils.go
core/container_authenticator.go
core/cp4d_authenticator.go
core/iam_authenticator.go
core/jwt_utils.go
core/mcsp_authenticator.go
core/request_builder.go
core/unmarshal_v2.go
core/utils.go
core/vpc_instance_authenticator.go

I missed an error origination point that needed to be converted to the new format. Also, this is maybe overly cautious but I added back in the original error instances as native caused by errors for all instances. Before, I intentionally left alone places that held an error origination from `fmt.Errorf()` because I don't know that users can really match against those, but I figured we might as well be as compatibility-friendly as we can be, since it doesn't cost us anything.

fix(errors): restore matching against all original errors

---

core/base_service.go

External authenticators may not use our error types. We previously assumed that errors coming from the `Authenticate` method would be either an `AuthenticationError` or `SDKProblem` and performed a type-cast that could cause a panic. This makes the type checking more explicit, and in the case of an unexpected error type, wraps the error in a new SDKProblem object and returns it to keep our error types consistent.

fix(errors): wrap errors from external authenticators to use new system

---

core/container_authenticator.go
core/container_authenticator_test.go
core/cp4d_authenticator.go
core/cp4d_authenticator_test.go
core/iam_authenticator.go
core/iam_authenticator_test.go
core/mcsp_authenticator.go
core/mcsp_authenticator_test.go
core/vpc_instance_authenticator.go
core/vpc_instance_authenticator_test.go

This commit updates our various request-based authenticators so that the User-Agent header is included with each outbound token request. The value of the User-Agent header will be of the form "ibm-go-sdk-core/<authenticator-type>-<core-version> <os-info>".

feat: send user-agent header with auth token requests

---

core/base_service.go

A typo resulted in a bug that prevents errors from being created in the event of external authenticators. This fixes the issue.

fix: use correct error variable in external auth case

---

core/base_service.go
core/http_problem.go
core/http_problem_test.go
core/sdk_problem.go
core/sdk_problem_test.go
core/sdk_problem_utils.go

Previously, any SDKProblem instance could be used as the "caused by" for another SDKProblem instance and its ID would become a part of the hash. This meant that problems created between service SDKs and the Go SDK Core would have a lot of complexity - the error scenarios tracked would be unnecessarily granular and numerous.
This change updates the system to maintain one problem scenario per *context* (where a context is either HTTP, SDK, or Terraform) rather than per every component within a given context.
It also provides for keeping knowledge of problem scenarios originating in the core for easier debugging and easier attaching of HTTP errors to service SDK problems.

fix(errors): flatten sdk problem chains to reduce hash complexity

---

Makefile
core/request_builder.go
core/sdk_problem_test.go
core/sdk_problem_utils.go

This commit modifies RequestBuilder.ResolveRequestURL() slightly so that the passed-in path string (unresolved, potentially containing special characters and path parameter references) is URL-encoded prior to replacing path param references with their corresponding encoded path param values.  This ensures that the URL string passed to http.NewRequest() by RequestBuilder.Build() will be properly encoded (escaped) such that all special characters appearing in path segments are converted to their %nn equivalents, but yet any escaped characters within the encoded path param values are NOT decoded.  This avoids a quirk in the url.Parse() method that is invoked by the http.NewRequest() method.
This change is needed in order to properly support a scenario where:
1. a path parameter value …

fix(request_builder): encode unresolved path string prior to path parameter insertion

---

go.mod
go.sum

https://github.com/advisories/GHSA-v6v8-xj6m-xwqh

chore(deps): bump go-retryablehttp v0.7.5 => v0.7.7

---

core/authentication_error_test.go
core/authenticator_factory.go
core/authenticator_factory_test.go
core/base_service.go
core/base_service_retries_test.go
core/base_service_test.go
core/basic_authenticator.go
core/basic_authenticator_test.go
core/bearer_token_authenticator.go
core/bearer_token_authenticator_test.go
core/common_test.go
core/config_utils.go
core/config_utils_test.go
core/container_authenticator.go
core/cp4d_authenticator.go
core/file_with_metadata_test.go
core/http_problem_test.go
core/iam_authenticator.go
core/ibm_problem_test.go
core/mcsp_authenticator.go
core/mcsp_authenticator_test.go
core/ordered_maps_test.go
core/parameterized_url.go
core/problem_utils_test.go
core/sdk_problem_test.go
core/vpc_instance_authenticator.go
core/vpc_instance_authenticator_test.go

This commit adds some debug logging in various
components, and also modifies some tests so that
it's easy to enable debug logging when running
individual sets of tests.

fix(logging): improve go core's debug logging

---

README.md

While working on the common sdk repo's README updates related to logging, I noticed that the Go core's README doesn't have a "Logging" section.  This commit fixes that.

docs: add logging section to README

---

.secrets.baseline
Authentication.md
README.md
core/authenticator_factory.go
core/authenticator_factory_test.go
core/common_test.go
core/constants.go
core/iam_assume_authenticator.go
core/iam_assume_authenticator_test.go
resources/my-credentials.env

This commit introduces the new IamAssumeAuthenticator which will fetch an IAM access token using the IAM getToken operation's "assume" grant type.  The resulting access token allows the application to assume the identity of a trusted profile, similar to the "sudo" feature of Linux.

feat(IamAssumeAuthenticator): introduce new authenticator type

---

core/utils.go

This PR contains a simple adjustment to error handling of the struct field validation.
Previously only the string representation of the error was included in the returned
`SDKError`, but an upcoming change to the CLI plugins requires the actual error
object, because it contains valuable information.

fix: wrap full validation errors instead of just their message

---

Authentication.md
README.md

The code examples in the README and Authentication documents used curly braces around the imports, when they should be parentheses.
This commit corrects all such typos.

docs: fix imports in examples

---

.secrets.baseline
core/base_service.go
core/base_service_test.go

This commit modifies the Go core's BaseService.Request() method slightly so that when setting service-level custom headers on the outbound request, it will now replace any existing header with the service-level header value, rather than add the service-level header value to the existing value that might already exist.
The net effect of this is that a User-Agent header set as a service-level default header will now override a User-Agent header set by an SDK project through its "common.GetSdkHeaders()" function.

fix(BaseService): allow User-Agent to be set via service-level headers
